# Generated by Django 3.2.8 on 2021-10-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='tweetmodel',
            name='session_key',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
