# Generated by Django 3.2.8 on 2021-10-31 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_auto_20211031_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweetmodel',
            old_name='tweet_file',
            new_name='tweets_array',
        ),
    ]
