# Generated by Django 3.2.8 on 2021-11-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_auto_20211031_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanTweetModel',
            fields=[
                ('session_key', models.TextField(primary_key=True, serialize=False)),
                ('user_handle', models.TextField()),
                ('clean_tweets_json', models.JSONField()),
                ('user_dep_class', models.FloatField()),
                ('user_anx_class', models.FloatField()),
                ('user_nan_class', models.FloatField()),
            ],
        ),
    ]
